/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package winthorDb.forms;

import java.util.List;
import winthorDb.error.MessageDialog;
import winthorDb.error.trataErro;
import winthorDb.oracleDb.IntegracaoWinthorDb;

/**
 *
 * @author ageurover
 */
public class Brz002 extends javax.swing.JFrame {

    /**
     * Creates new form Brz001
     */
    public Brz002() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/winthorDb/forms/RoverTecnologiaIcone.png")).getImage());
    }

    private void buscaLancamentoWinthor(String codFornec, String numNota, String codFilial) {
        IntegracaoWinthorDb wint = new IntegracaoWinthorDb();

        try {
            String strSelect = "SELECT PCLANC.codfilial, PCLANC.recnum,PCLANC.numnota, PCLANC.dtlanc, PCLANC.codfornec, PCFORNEC.fornecedor,"
                    + " PCLANC.valor, PCLANC.dtvenc, PCLANC.historico "
                    + " FROM PCLANC, PCFORNEC "
                    + " WHERE PCLANC.codfornec = PCFORNEC.codfornec"
                    + " AND PCLANC.NUMNOTA = " + numNota
                    + " AND PCLANC.CODFORNEC = " + codFornec
                    + " AND PCLANC.CODFILIAL = " + codFilial;

            wint.openConectOracle();
            List lst = wint.selectDados(strSelect);

            edtDetalhePedido.setText("");
            edtDetalhePedido.append("Lançamentos Encontrados no Winthor\n");

            for (Object object : lst.toArray()) {
                edtDetalhePedido.append(lst.size() + "\n");
                edtDetalhePedido.append(object.toString() + "\n");
            }
            if (lst.isEmpty()) {
                edtDetalhePedido.append("O Lançamento não foi localizado\n");
            }
            lst = null;
            wint.closeConectOracle();

        } catch (Exception ex) {
            trataErro.trataException(ex);
        }

    }

    private void baixaLancamento(String numNota, String codFornec, String codFilial, String numConta) throws Exception {
        IntegracaoWinthorDb wint = new IntegracaoWinthorDb();

        int result = 0;
        try {
            wint.openConectOracle();
            // passo 1 - Alterar os dados do lançamento fazendo a baixa no sistema
            String updString = "UPDATE PCLANC SET VPAGO = VALOR, DTPAGTO = DTVENC, CODCONTA = " + numConta
                    + " WHERE CODFORNEC = " + codFornec
                    + " AND NUMNOTA = " + numNota
                    + " AND CODFILIAL = " + codFilial;

            result = wint.updateDados(updString);
            if (result > 0) {
                edtDetalhePedido.append("[" + result + "] Titulos Alterados: " + result + "\n");
                edtDetalhePedido.append("Os lançamentos foram atualizado na base de dados do winthor\n");
                wint.closeConectOracle();
            }
        } catch (Exception ex) {
            trataErro.trataException(ex);
            throw ex;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        edtNumeroNota = new javax.swing.JTextField();
        btnPesquisaPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDetalhePedido = new javax.swing.JTextArea();
        btnVinculaTitulo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edtCodFilial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtCodContaContabil = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        edtCodFornec = new javax.swing.JTextField();

        setTitle("Conversão de Pedidos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winthorDb/forms/RoverTecnologiaIcone.png"))); // NOI18N
        jLabel2.setToolTipText("Brz002");

        jLabel1.setText("Baixa Lançamentos Financeiros de Entrada de Produção");

        jLabel3.setText("* * Rotina do Auto Serviço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe os dados do pedido"));

        jLabel4.setText("Núm.Nota:");

        btnPesquisaPedido.setText("Pesquisar");
        btnPesquisaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaPedidoActionPerformed(evt);
            }
        });

        edtDetalhePedido.setColumns(20);
        edtDetalhePedido.setRows(5);
        edtDetalhePedido.setWrapStyleWord(true);
        jScrollPane1.setViewportView(edtDetalhePedido);

        btnVinculaTitulo.setText("Baixar Lançamento");
        btnVinculaTitulo.setEnabled(false);
        btnVinculaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVinculaTituloActionPerformed(evt);
            }
        });

        jLabel5.setText("Cod. Filial:");

        edtCodFilial.setText("1");
        edtCodFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodFilialActionPerformed(evt);
            }
        });

        jLabel6.setText("Cod. Conta:");

        edtCodContaContabil.setEditable(false);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel7.setText("Cod.Fornec:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPesquisaPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodContaContabil, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVinculaTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 242, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCodFornec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(edtCodFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(edtNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisaPedido)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtCodContaContabil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVinculaTitulo)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaPedidoActionPerformed
        try {
            if ((!edtNumeroNota.getText().isEmpty()) && (!edtCodFornec.getText().isEmpty()) && (!edtCodFilial.getText().isEmpty())) {
                buscaLancamentoWinthor(edtCodFornec.getText(), edtNumeroNota.getText(), edtCodFilial.getText());
                btnPesquisaPedido.setEnabled(false);
                edtNumeroNota.setEditable(false);
                edtCodFilial.setEditable(false);
                btnVinculaTitulo.setEnabled(true);
                edtCodContaContabil.setEditable(true);
            } else {
                trataErro.lstErros.clear();
                trataErro.addListaErros("ATENÇÃO: Deve ser informado o numero da Nota, o codigo do Fornecedor e o codigo da filial!");
                trataErro.mostraListaErros();
                trataErro.lstErros.clear();
                btnLimparActionPerformed(evt);
            }
        } catch (Exception ex) {
            trataErro.trataException(ex);
        }
    }//GEN-LAST:event_btnPesquisaPedidoActionPerformed

    private void edtCodFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodFilialActionPerformed

    }//GEN-LAST:event_edtCodFilialActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        btnPesquisaPedido.setEnabled(true);
        edtNumeroNota.setEditable(true);
        edtCodFilial.setEditable(true);
        btnVinculaTitulo.setEnabled(false);
        edtCodContaContabil.setEditable(false);
        edtCodFilial.setText("1");
        edtNumeroNota.setText("");
        edtCodContaContabil.setText("");
        edtDetalhePedido.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVinculaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVinculaTituloActionPerformed
        try {
            if ((!edtNumeroNota.getText().isEmpty()) && (!edtCodContaContabil.getText().isEmpty()) && (!edtCodFilial.getText().isEmpty()) && (!edtCodFornec.getText().isEmpty())) {
                baixaLancamento(edtNumeroNota.getText(), edtCodFornec.getText(), edtCodFilial.getText(), edtCodContaContabil.getText());
                MessageDialog.info("Baixa dos Lançamentos Realizada! \n" + edtDetalhePedido.getText());
                btnLimparActionPerformed(evt);
            } else {
                trataErro.lstErros.clear();
                trataErro.addListaErros("ATENÇÃO: Deve ser informado o numero da nota, o codigo do fornecedor, o numero da conta contabil e o codigo da filial!");
                trataErro.mostraListaErros();
                trataErro.lstErros.clear();
                btnLimparActionPerformed(evt);
            }
        } catch (Exception ex) {
            trataErro.trataException(ex);
        }
    }//GEN-LAST:event_btnVinculaTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brz002.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Brz002().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisaPedido;
    private javax.swing.JButton btnVinculaTitulo;
    private javax.swing.JTextField edtCodContaContabil;
    private javax.swing.JTextField edtCodFilial;
    private javax.swing.JTextField edtCodFornec;
    private javax.swing.JTextArea edtDetalhePedido;
    private javax.swing.JTextField edtNumeroNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
