/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package winthorDb.forms;

import java.util.logging.Level;
import java.util.logging.Logger;
import winthorDb.Main;
import winthorDb.forms.coletor.consultaOS;
import winthorDb.forms.coletor.vinculaEnderecoLoja;
import winthorDb.forms.dre.DreGrupoConta;

/**
 *
 * @author ageurover
 */
public class Brz000 extends javax.swing.JFrame {

    /**
     * Creates new form Brz000
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Brz000() {
        initComponents();
        setLocationRelativeTo(null);
        lblVersao.setText("Versão: " + Main.versao );
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/winthorDb/forms/RoverTecnologiaIcone.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRotinas = new javax.swing.JMenu();
        mnuVendas = new javax.swing.JMenu();
        mnuProcessoPedidoCarga = new javax.swing.JMenuItem();
        mnuProcessoPedidoCupom = new javax.swing.JMenuItem();
        mnuAtualizaBarrasPedido = new javax.swing.JMenuItem();
        mnuPedidoViradaMes = new javax.swing.JMenuItem();
        mnuFilialFaturaCarga = new javax.swing.JMenuItem();
        mnuProcessoDevolucaoCupom = new javax.swing.JMenuItem();
        mnuCadastroSintegra = new javax.swing.JMenuItem();
        mnuEstoque = new javax.swing.JMenu();
        mnuAtualizaCustoFilial = new javax.swing.JMenuItem();
        mnuProcessarImagens = new javax.swing.JMenuItem();
        mnuBaixaLancProducao = new javax.swing.JMenuItem();
        mnuAjusteEstoqueFilial90 = new javax.swing.JMenuItem();
        mnuConversaoEmbalagem = new javax.swing.JMenuItem();
        mnuValidaEan = new javax.swing.JMenuItem();
        mnuFinanceiro = new javax.swing.JMenu();
        mnuExportaProtesto = new javax.swing.JMenuItem();
        mnuImportaFolhaCnab240 = new javax.swing.JMenuItem();
        mnuDreGrupoConta = new javax.swing.JMenuItem();
        mnuExportacao = new javax.swing.JMenu();
        mnuExport_3coracoesConEmb31 = new javax.swing.JMenuItem();
        mnuExport_3coracoesDocCob30a = new javax.swing.JMenuItem();
        mnuNotaServico = new javax.swing.JMenuItem();
        mnuExpNs_conemb31 = new javax.swing.JMenuItem();
        mnuExpNs_doccob30a = new javax.swing.JMenuItem();
        mnuColetor = new javax.swing.JMenu();
        mnuConsultaOs = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuContabil = new javax.swing.JMenu();
        mnuImportarSped = new javax.swing.JMenuItem();
        mnuConfig = new javax.swing.JMenu();
        mnuConfigDb = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intergrado (kimtec -> Winthor)");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winthorDb/forms/RoverTecnologiaIcone.png"))); // NOI18N
        jLabel1.setText("www.kimtec.com.br");

        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersao.setText("Versão:");

        jMenuRotinas.setText("Menu");

        mnuVendas.setText("Vendas");

        mnuProcessoPedidoCarga.setText("Processo Pedido/Cupom (Carga)");
        mnuProcessoPedidoCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcessoPedidoCargaActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuProcessoPedidoCarga);

        mnuProcessoPedidoCupom.setText("Processo Pedido/Cupom (Pedido)");
        mnuProcessoPedidoCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcessoPedidoCupomActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuProcessoPedidoCupom);

        mnuAtualizaBarrasPedido.setText("Atualiza Cod. Barras Pedido Venda");
        mnuAtualizaBarrasPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizaBarrasPedidoActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuAtualizaBarrasPedido);

        mnuPedidoViradaMes.setText("Ajusta Data Pedido Virada Mês");
        mnuPedidoViradaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPedidoViradaMesActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuPedidoViradaMes);

        mnuFilialFaturaCarga.setText("Processo Filial Fatura por Carregamento");
        mnuFilialFaturaCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFilialFaturaCargaActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuFilialFaturaCarga);

        mnuProcessoDevolucaoCupom.setText("Processo Devolução Cupom Fiscal");
        mnuProcessoDevolucaoCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcessoDevolucaoCupomActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuProcessoDevolucaoCupom);

        mnuCadastroSintegra.setText("Cadastro de Cliente Sintegra");
        mnuCadastroSintegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroSintegraActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuCadastroSintegra);

        jMenuRotinas.add(mnuVendas);

        mnuEstoque.setText("Estoque");

        mnuAtualizaCustoFilial.setText("Atualiza Custo Transferencia");
        mnuAtualizaCustoFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizaCustoFilialActionPerformed(evt);
            }
        });
        mnuEstoque.add(mnuAtualizaCustoFilial);

        mnuProcessarImagens.setText("Processar Imagens de Produtos");
        mnuProcessarImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcessarImagensActionPerformed(evt);
            }
        });
        mnuEstoque.add(mnuProcessarImagens);

        mnuBaixaLancProducao.setText("Baixa Lançamento Entrada Producao");
        mnuBaixaLancProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBaixaLancProducaoActionPerformed(evt);
            }
        });
        mnuEstoque.add(mnuBaixaLancProducao);

        mnuAjusteEstoqueFilial90.setText("Ajuste Estoque Filial 90 para Filial Retira");
        mnuAjusteEstoqueFilial90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjusteEstoqueFilial90ActionPerformed(evt);
            }
        });
        mnuEstoque.add(mnuAjusteEstoqueFilial90);

        mnuConversaoEmbalagem.setText("Conversão de Embagem (Master/Unidade)");
        mnuConversaoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConversaoEmbalagemActionPerformed(evt);
            }
        });
        mnuEstoque.add(mnuConversaoEmbalagem);

        mnuValidaEan.setText("Validação EAN 8/13");
        mnuValidaEan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuValidaEanActionPerformed(evt);
            }
        });
        mnuEstoque.add(mnuValidaEan);

        jMenuRotinas.add(mnuEstoque);

        mnuFinanceiro.setText("Financeiro");

        mnuExportaProtesto.setText("Exportação Dados Protesto de Titulos");
        mnuExportaProtesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExportaProtestoActionPerformed(evt);
            }
        });
        mnuFinanceiro.add(mnuExportaProtesto);

        mnuImportaFolhaCnab240.setText("Importação Folha Pagamento (CNAB-240)");
        mnuImportaFolhaCnab240.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportaFolhaCnab240ActionPerformed(evt);
            }
        });
        mnuFinanceiro.add(mnuImportaFolhaCnab240);

        mnuDreGrupoConta.setText("DRE - Grupo Conta");
        mnuDreGrupoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDreGrupoContaActionPerformed(evt);
            }
        });
        mnuFinanceiro.add(mnuDreGrupoConta);

        jMenuRotinas.add(mnuFinanceiro);

        mnuExportacao.setText("Exportação 3C");

        mnuExport_3coracoesConEmb31.setText("3 Corações CONEMB  3.1");
        mnuExport_3coracoesConEmb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExport_3coracoesConEmb31ActionPerformed(evt);
            }
        });
        mnuExportacao.add(mnuExport_3coracoesConEmb31);

        mnuExport_3coracoesDocCob30a.setText("3 Corações DOCCOB 3.0A");
        mnuExport_3coracoesDocCob30a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExport_3coracoesDocCob30aActionPerformed(evt);
            }
        });
        mnuExportacao.add(mnuExport_3coracoesDocCob30a);

        mnuNotaServico.setText("Nota de Serviço");
        mnuNotaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNotaServicoActionPerformed(evt);
            }
        });
        mnuExportacao.add(mnuNotaServico);

        mnuExpNs_conemb31.setText("Exp. Nota Serv CONEMB 3.1");
        mnuExpNs_conemb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExpNs_conemb31ActionPerformed(evt);
            }
        });
        mnuExportacao.add(mnuExpNs_conemb31);

        mnuExpNs_doccob30a.setText("Exp. Nota Serv DOCCOB 3.0A");
        mnuExpNs_doccob30a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExpNs_doccob30aActionPerformed(evt);
            }
        });
        mnuExportacao.add(mnuExpNs_doccob30a);

        jMenuRotinas.add(mnuExportacao);

        mnuColetor.setText("Coletor");

        mnuConsultaOs.setText("Consulta OS");
        mnuConsultaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaOsActionPerformed(evt);
            }
        });
        mnuColetor.add(mnuConsultaOs);

        jMenuItem4.setText("Endereço Loja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuColetor.add(jMenuItem4);

        jMenuRotinas.add(mnuColetor);

        mnuContabil.setText("Contabilidade");

        mnuImportarSped.setText("Importar Sped");
        mnuImportarSped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportarSpedActionPerformed(evt);
            }
        });
        mnuContabil.add(mnuImportarSped);

        jMenuRotinas.add(mnuContabil);

        mnuConfig.setText("Configuração");

        mnuConfigDb.setText("Conexão Banco de Dados");
        mnuConfigDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConfigDbActionPerformed(evt);
            }
        });
        mnuConfig.add(mnuConfigDb);

        jMenuRotinas.add(mnuConfig);

        jMenuBar1.add(jMenuRotinas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(lblVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuConfigDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConfigDbActionPerformed
        Main.dialog = new BrzConfigDb();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuConfigDbActionPerformed

    private void mnuProcessoPedidoCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcessoPedidoCupomActionPerformed
        Main.dialog = new Brz003();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuProcessoPedidoCupomActionPerformed

    private void mnuConversaoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConversaoEmbalagemActionPerformed
        Main.dialog = new Brz005();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuConversaoEmbalagemActionPerformed

    private void mnuProcessarImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcessarImagensActionPerformed
        try {
            Main.dialog = new Brz006();
        } catch (Exception ex) {
            Logger.getLogger(Brz000.class.getName()).log(Level.SEVERE, null, ex);
        }
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuProcessarImagensActionPerformed

    private void mnuProcessoDevolucaoCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcessoDevolucaoCupomActionPerformed
        Main.dialog = new Brz007();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuProcessoDevolucaoCupomActionPerformed

    private void mnuProcessoPedidoCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcessoPedidoCargaActionPerformed
        Main.dialog = new Brz009();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuProcessoPedidoCargaActionPerformed

    private void mnuPedidoViradaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPedidoViradaMesActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz010();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuPedidoViradaMesActionPerformed

    private void mnuAjusteEstoqueFilial90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjusteEstoqueFilial90ActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz004();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuAjusteEstoqueFilial90ActionPerformed

    private void mnuConsultaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaOsActionPerformed
        Main.dialog = new consultaOS();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuConsultaOsActionPerformed

    private void mnuFilialFaturaCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFilialFaturaCargaActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz0012();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuFilialFaturaCargaActionPerformed

    private void mnuBaixaLancProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBaixaLancProducaoActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz002();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuBaixaLancProducaoActionPerformed

    private void mnuValidaEanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuValidaEanActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz011();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuValidaEanActionPerformed

    private void mnuExportaProtestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExportaProtestoActionPerformed
        // TODO add your handling code here:
        winthorDb.forms.etl.cartorio.ExportDocDialog.open(9999, "CART", "0");
    }//GEN-LAST:event_mnuExportaProtestoActionPerformed

    private void mnuImportaFolhaCnab240ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportaFolhaCnab240ActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz013();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuImportaFolhaCnab240ActionPerformed

    private void mnuCadastroSintegraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroSintegraActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz008();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuCadastroSintegraActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Main.dialog = new vinculaEnderecoLoja();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnuAtualizaBarrasPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizaBarrasPedidoActionPerformed
        Main.dialog = new Brz014();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuAtualizaBarrasPedidoActionPerformed

    private void mnuExport_3coracoesConEmb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExport_3coracoesConEmb31ActionPerformed
        // TODO add your handling code here:
        winthorDb.forms.etl.cafe3Coracoes.ExportDocDialog.open(9001, "3COR_CONEMB_31", "0");
    }//GEN-LAST:event_mnuExport_3coracoesConEmb31ActionPerformed

    private void mnuExport_3coracoesDocCob30aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExport_3coracoesDocCob30aActionPerformed
        winthorDb.forms.etl.cafe3Coracoes.ExportDocDialog.open(9001, "3COR_DOCCOB_30A", "0");
    }//GEN-LAST:event_mnuExport_3coracoesDocCob30aActionPerformed

    private void mnuDreGrupoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDreGrupoContaActionPerformed
        // TODO add your handling code here:
        Main.dialog = new DreGrupoConta();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuDreGrupoContaActionPerformed

    private void mnuImportarSpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportarSpedActionPerformed
        Main.dialog = new Brz015();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuImportarSpedActionPerformed

    private void mnuNotaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNotaServicoActionPerformed
        winthorDb.forms.etl.cafe3Coracoes.LancarNotaServico.open();
    }//GEN-LAST:event_mnuNotaServicoActionPerformed

    private void mnuExpNs_conemb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExpNs_conemb31ActionPerformed
        winthorDb.forms.etl.cafe3Coracoes.ExportDocNfsDialog.open(9002, "NS_3COR_CONEMB_31", "0");
    }//GEN-LAST:event_mnuExpNs_conemb31ActionPerformed

    private void mnuExpNs_doccob30aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExpNs_doccob30aActionPerformed
        // TODO add your handling code here:
        winthorDb.forms.etl.cafe3Coracoes.ExportDocNfsDialog.open(9002, "NS_3COR_DOCCOB_30A", "0");
    }//GEN-LAST:event_mnuExpNs_doccob30aActionPerformed

    private void mnuAtualizaCustoFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizaCustoFilialActionPerformed
        // TODO add your handling code here:
        Main.dialog = new Brz016();
        Main.dialog.setVisible(true);
    }//GEN-LAST:event_mnuAtualizaCustoFilialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brz000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brz000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brz000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brz000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Brz000().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuRotinas;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JMenuItem mnuAjusteEstoqueFilial90;
    private javax.swing.JMenuItem mnuAtualizaBarrasPedido;
    private javax.swing.JMenuItem mnuAtualizaCustoFilial;
    private javax.swing.JMenuItem mnuBaixaLancProducao;
    private javax.swing.JMenuItem mnuCadastroSintegra;
    private javax.swing.JMenu mnuColetor;
    private javax.swing.JMenu mnuConfig;
    private javax.swing.JMenuItem mnuConfigDb;
    private javax.swing.JMenuItem mnuConsultaOs;
    private javax.swing.JMenu mnuContabil;
    private javax.swing.JMenuItem mnuConversaoEmbalagem;
    private javax.swing.JMenuItem mnuDreGrupoConta;
    private javax.swing.JMenu mnuEstoque;
    private javax.swing.JMenuItem mnuExpNs_conemb31;
    private javax.swing.JMenuItem mnuExpNs_doccob30a;
    private javax.swing.JMenuItem mnuExport_3coracoesConEmb31;
    private javax.swing.JMenuItem mnuExport_3coracoesDocCob30a;
    private javax.swing.JMenuItem mnuExportaProtesto;
    private javax.swing.JMenu mnuExportacao;
    private javax.swing.JMenuItem mnuFilialFaturaCarga;
    private javax.swing.JMenu mnuFinanceiro;
    private javax.swing.JMenuItem mnuImportaFolhaCnab240;
    private javax.swing.JMenuItem mnuImportarSped;
    private javax.swing.JMenuItem mnuNotaServico;
    private javax.swing.JMenuItem mnuPedidoViradaMes;
    private javax.swing.JMenuItem mnuProcessarImagens;
    private javax.swing.JMenuItem mnuProcessoDevolucaoCupom;
    private javax.swing.JMenuItem mnuProcessoPedidoCarga;
    private javax.swing.JMenuItem mnuProcessoPedidoCupom;
    private javax.swing.JMenuItem mnuValidaEan;
    private javax.swing.JMenu mnuVendas;
    // End of variables declaration//GEN-END:variables
}
