/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package winthorDb.forms.coletor;

import java.awt.event.KeyEvent;
import winthorDb.Main;
import winthorDb.error.MessageDialog;
import winthorDb.error.trataErro;
import winthorDb.oracleDb.IntegracaoWinthorDb;
import winthorDb.util.Formato;

/**
 *
 * @author ageurover
 */
public class consultaOS extends javax.swing.JFrame {

    int qtdCheque = 0;

    /**
     * Creates new form Brz001
     */
    public consultaOS() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/winthorDb/forms/RoverTecnologiaIcone.png")).getImage());
    }

    /**
     * Faz a busca dos dados do pedido no sistema winthor para que seja
     * confirmado pelo usuario.
     *
     * @param numCarga Numero do pedido digitado no sistema winthor
     *
     */
    private void buscaOsWinthor(String codfilial, String numOs) throws Exception {
        IntegracaoWinthorDb wint = new IntegracaoWinthorDb();

        try {
            String strSelect = "SELECT "
                    + "        M.CODPROD\n"
                    + "       ,P.DESCRICAO\n"
                    + "       ,P.embalagem\n"
                    + "       ,SUM(NVL(M.QT,0)) QT\n"
                    + "       ,SUM(NVL(M.QTCONFERIDA,0)) QTCONFERIDA\n"
                    + "       ,SUM(NVL(M.QTCONFERIDA,0)) - SUM(nvl(M.QT,0)) QTDIVERGENTE\n"
                    + "       , M.NUMOS\n ,M.NUMCAR\n"
                    + "       ,M.NUMPALETE\n"
                    + "       ,M.TIPOOS\n"
                    + "       ,M.CODFUNCCONF\n"
                    + "       ,M.NUMBOX\n"
                    + "       ,(SELECT NOME FROM PCEMPR WHERE MATRICULA=M.CODFUNCCONF) NOMECONFERENTE\n"
                    + "       ,(SELECT NOME FROM PCEMPR WHERE MATRICULA=M.CODFUNCOS) NOMESEPARADOR\n"
                    + " FROM PCMOVENDPEND M, PCPRODUT P, PCENDERECO E\n"
                    + " WHERE     M.CODPROD=P.CODPROD\n"
                    + "       AND M.DTESTORNO IS NULL \n"
                    + "       AND (select codendereco from pcprodutpicking where codprod=p.codprod \n"
                    + "             and codfilial=m.codfilial and tipo='V') = E.CODENDERECO\n"
                    + "       AND M.CODOPER = 'S' AND M.posicao IN ('P') \n"
                    + "       AND M.NUMOS = " + Formato.somenteNumeros(numOs)
                    + "       AND M.CODFILIAL = '" + Formato.somenteNumeros(codfilial) + "' "
                    + " GROUP BY M.NUMOS\n"
                    + "       ,M.NUMCAR\n"
                    + "       ,M.CODPROD\n"
                    + "       ,M.NUMPALETE\n"
                    + "       ,P.DESCRICAO\n"
                    + "       ,P.embalagem\n"
                    + "       ,M.TIPOOS\n"
                    + "       ,M.NUMBOX\n"
                    + "       ,M.CODFUNCCONF\n"
                    + "       ,M.CODFUNCOS\n"
                    + " ORDER BY P.DESCRICAO";

            wint.openConectOracle();
            tblOs.clearTableData();
            tblOs.setTableData(wint.selectResultSet(strSelect));

            if (tblOs.getRowCount() <= 0) {
                MessageDialog.info("Registros não localizados!");
            }

        } catch (Exception ex) {
            trataErro.trataException(ex, "buscaOsWinthor");
        } finally {
            wint.closeConectOracle();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblOs = new winthorDb.util.CustomTable();
        jLabel6 = new javax.swing.JLabel();
        edtNrOs = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();

        setTitle("Consulta Nr. OS");
        setMinimumSize(new java.awt.Dimension(350, 370));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblOs.setToolTipText("");
        tblOs.setCellSelectionEnabled(true);
        tblOs.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jScrollPane3.setViewportView(tblOs);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel6.setText("Nr. OS:");

        edtNrOs.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        edtNrOs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNrOsKeyPressed(evt);
            }
        });

        btnPesquisa.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNrOs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisa)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtNrOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        try {
            if (!edtNrOs.getText().isEmpty()) {
                buscaOsWinthor(Main.codFilial, edtNrOs.getText());
            }
        } catch (Exception ex) {
            trataErro.trataException(ex, "btnPesquisaActionPerformed");

        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void edtNrOsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNrOsKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ACCEPT) {
                if (!edtNrOs.getText().isEmpty()) {
                    buscaOsWinthor(Main.codFilial, edtNrOs.getText());
                }
            }
        } catch (Exception ex) {
            trataErro.trataException(ex, "btnPesquisaActionPerformed");

        }
    }//GEN-LAST:event_edtNrOsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            trataErro.trataException(ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new consultaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JTextField edtNrOs;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private winthorDb.util.CustomTable tblOs;
    // End of variables declaration//GEN-END:variables
}
