/*
 * ErroDialog.java
 *
 * Created on February 20, 2008, 10:43 PM
 */
package winthorDb.error;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JTextArea;
import winthorDb.util.Formato;

/**
 *
 * @author  eduardo
 */
public class ErroDialog extends javax.swing.JDialog {

    /** Creates new form ErroDialog
     * @param parent
     * @param modal */
    public ErroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    private JTextArea getTxt() {
        return txtErro;
    }

    public static void abrir(Exception ex) {
        ErroDialog e = new ErroDialog(null, true);
        String strErro = "";
        strErro = "\n#Mensagem de Erro\n";
        strErro += Formato.replicate("*", 50) + "\n#Mensagem de Erro\n\t";
        strErro += ex.getMessage() + "\n";
        strErro += Formato.replicate("-", 50) + "\n#Localizacao da Mensagem\n\t";
        strErro += ex.getLocalizedMessage() + "\n";
        strErro += Formato.replicate("-", 50) + "\n#Texto da Mensagem\n\t";
        strErro += ex.toString();

        e.getTxt().setText(strErro);

        e.setVisible(true);
        e.pack();
    }

    public static void abrir(ArrayList lst) {
        String strErro = "";
        ErroDialog e = new ErroDialog(null, true);
        strErro = "#Lista de Erros\n";
        strErro += Formato.replicate("-", 50) + "\n";
        if (!lst.isEmpty()) {
            for (Object lst1 : lst) {
                strErro += "\n" + lst1.toString();
            }
        }
        e.getTxt().setText(strErro);
        e.setVisible(true);
        e.pack();
    }

    public static void abrir(Exception ex, String complemento) {
        String strErro = "";
        ErroDialog e = new ErroDialog(null, true);
        strErro += "\n#Aviso\n\t";
        strErro += complemento + "\n";
        strErro += Formato.replicate("*", 50) + "\n#Mensagem de Erro\n\t";
        strErro += ex.getMessage() + "\n";
        strErro += Formato.replicate("+", 50) + "\n#Localizacao da Mensagem\n\t";
        strErro += ex.getLocalizedMessage() + "\n";
        strErro += Formato.replicate("=", 50) + "\n#Texto da Mensagem\n\t";
        strErro += ex.toString();

        e.getTxt().setText(strErro);

        e.setVisible(true);
        e.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtErro = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Erro de Sistema");
        setAlwaysOnTop(true);
        setModal(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Erro"));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtErro.setColumns(20);
        txtErro.setLineWrap(true);
        txtErro.setRows(5);
        txtErro.setWrapStyleWord(true);
        txtErro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtErroKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtErro);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }

}//GEN-LAST:event_formKeyPressed

    private void txtErroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErroKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_TAB)) {
            txtErro.transferFocus();
        }
    }//GEN-LAST:event_txtErroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ErroDialog dialog = new ErroDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtErro;
    // End of variables declaration//GEN-END:variables
}
