/*
 * ErroDialog.java
 *
 * Created on February 20, 2008, 10:43 PM
 */
package integradorbrasil;

import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author  eduardo
 */
public class ErroDialog extends javax.swing.JDialog {

    /** Creates new form ErroDialog */
    public ErroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    private JTextArea getTxt() {
        return txtErro;
    }

    public static void abrir(Exception ex) {
        ErroDialog e = new ErroDialog(Main.mainWindow, true);
        String strErro = "";
        strErro = "\n#Mensagem de Erro\n";
        strErro += Formato.replicate("*", 50) + "\n#Mensagem de Erro\n\t";
        strErro += ex.getMessage() + "\n";
        strErro += Formato.replicate("-", 50) + "\n#Localiza��o da Mensagem\n\t";
        strErro += ex.getLocalizedMessage() + "\n";
        strErro += Formato.replicate("-", 50) + "\n#Texto da Mensagem\n\t";
        strErro += ex.toString();

        e.getTxt().setText(strErro);

        e.setVisible(true);
        e.pack();
    }

    public static void abrir(ArrayList lst) {
        String strErro = "";
        ErroDialog e = new ErroDialog(Main.mainWindow, true);
        strErro = "#Lista de Erros\n";
        strErro += Formato.replicate("-", 50) + "\n";
        if (!lst.isEmpty()) {
            for (int i = 0; i < lst.size(); i++) {
                strErro += "\n" + lst.get(i).toString();
            }
        }
        e.getTxt().setText(strErro);
        e.setVisible(true);
        e.pack();
    }

    public static void abrir(Exception ex, String complemento) {
        String strErro = "";
        ErroDialog e = new ErroDialog(Main.mainWindow, true);
        strErro += "\n#Aviso\n\t";
        strErro += complemento + "\n";
        strErro += Formato.replicate("*", 50) + "\n#Mensagem de Erro\n\t";
        strErro += ex.getMessage() + "\n";
        strErro += Formato.replicate("+", 50) + "\n#Localiza��o da Mensagem\n\t";
        strErro += ex.getLocalizedMessage() + "\n";
        strErro += Formato.replicate("=", 50) + "\n#Texto da Mensagem\n\t";
        strErro += ex.toString();

        e.getTxt().setText(strErro);

        e.setVisible(true);
        e.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtErro = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Erro de Sistema");
        setAlwaysOnTop(true);
        setModal(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Erro"));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtErro.setColumns(20);
        txtErro.setLineWrap(true);
        txtErro.setRows(5);
        txtErro.setWrapStyleWord(true);
        txtErro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtErroKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtErro);

        jLabel1.setText("*É recomendado salvar detalhes do erro para envio ao suporte.");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        dispose();
    }

}//GEN-LAST:event_formKeyPressed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    FileWriter file = null;
    try {
        JFileChooser jfc = new JFileChooser();
        //abre janela para pastas
        int ret = jfc.showOpenDialog(null);
        if (ret == JFileChooser.APPROVE_OPTION) {
            String val = jfc.getSelectedFile().getAbsolutePath();
            file = new FileWriter(val);
            file.append(txtErro.getText().toString());
            file.flush();
            file.close();
            MessageDialog.info("Log Salvo em :\n" + val);
        }

    } catch (IOException ex) {
        trataErro.trataException(ex);
    }
    file = null;
}//GEN-LAST:event_jButton2ActionPerformed

    private void txtErroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErroKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_TAB)) {
            txtErro.transferFocus();
        }
    }//GEN-LAST:event_txtErroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ErroDialog dialog = new ErroDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtErro;
    // End of variables declaration//GEN-END:variables
}
